inherit_from: configs/Own/own.yaml
cam:
  H: 1080
  W: 1920
  fx: 808.080808081
  fy: 808.080808081
  cx: 960
  cy: 540
  png_depth_scale: 100.0 # cm2m for depth image in png format
  crop_edge: 0
mapping:
  bound:  [[-2.2,3],[-1,4],[-4,1.5]]
  marching_cubes_bound: [[-2.2,3],[-1,4],[-4,1.5]]
data:
  input_folder: Datasets/Own/scene7
  output: output/Own/scene7